export const communityCategories: CommunityCategory[] = [
  'Technology',
  'Design',
  'Business & Entrepreneurship',
  'Science',
  'Health & Fitness',
  'Gaming',
  'Art & Creativity',
  'Music',
  'Education',
  'Language Learning',
  'Travel',
  'Cooking & Food',
  'Sports',
  'Parenting',
  'Environment & Sustainability',
  'Fashion & Beauty',
  'History & Archaeology',
  'Anime & Manga',
  'Philosophy & Ethics',
  'Hobbies & DIY',
];
